title: Color Annotation Labeling
type: custom
group: Computer Vision
image: /static/templates/image-classification.png
details: <h1>label color pallets</h1>
config: '<View>
  <Image name="image" value="$image" zoom="true" zoomControl="true" rotateControl="true"/>

  <<Choices name="colors"
                      toName="image"
                      showInLine="true"
                      required="true"
                      choice="single">

              <View style="width:100%">
                <Header name="heading-colors" value="color (Select Applicable)" />
              </View>
              <Choice value="yellow"/>
              <Choice value="green"/>
              <Choice value="blue"/>
              <Choice value="red"/>
              <Choice value="white"/>
              <Choice value="black"/>
              <Choice value="purple"/>
              <Choice value="magenta"/>
            <Choice value="not applicable/not visible"/>
            </Choices>
    </View>'