title: Men Shoes Set3 Annotation
type: custom
group: Computer Vision
image: /static/templates/image-classification.png
details: <h1>Men Shoes Attributes</h1>
config: '<View>
    <Header value="Men Shoes Attributes Set 3"/>
    #**********************Department**************************
    <View style="display: flex;"> 
        <View style="flex: 70%">
          <Image name="image" value="$data" zoom="true" zoomControl="true" rotateControl="true"/>
        </View>
        <View style="flex: 30%">
            <Header name="heading-department" value="Department [Single-Option]"/>
            <Choices name="department" toName="image" showInLine="true" required="true" choice="single-radio">
              
            <Choice value="men_shoes"/>
            
              <Choice value="tag"/>
              <Choice value="other"/>
            </Choices>
        </View>
    </View>
    
    
    
    
    #**************************Upper Material [single-Option]*****************************
    
    <View style="display: flex;" visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
      <View style="flex: 70%">
        <Image name="image0" value="$data" zoom="true" zoomControl="true" rotateControl="true"/>
      </View>
      <View style="flex: 30%">
        <Choices name="upper_material" toName="image" showInLine="true" required="true" choice="single-radio">
          <View style="width:100%">
            <Header name="heading-upper_material" value="Select Upper Material [Single-Option]"/>
          </View>
          
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="camel"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="cashmere"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="cork"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="cotton_blend"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="cotton"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="fabric"/>
          </View>
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="synthetic"/>
          </View>   
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="faux_fur"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="faux_leather"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="faux_suede"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="fur"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="leather"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="linen"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="mesh"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="nubuck"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="nylon"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="patent_leather"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="plastic"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="polyester"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="polyurethane"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="pvc"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="rubber"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="spandex"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="suede"/>
          </View>

       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="wool"/>
          </View>
       
          
          <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
            <Choice value="Not-Applicable/Visible"/>
          </View>
        </Choices>
      </View>
    </View>
    
    
    
    
    #**************************Theme [single-Option]*****************************
    
    <View style="display: flex;" visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
      <View style="flex: 70%">
        <Image name="image1" value="$data" zoom="true" zoomControl="true" rotateControl="true"/>
      </View>
      <View style="flex: 30%">
        <Choices name="theme" toName="image" showInLine="true" required="true" choice="single-radio">
          <View style="width:100%">
            <Header name="heading-theme" value="Select Theme [Single-Option]"/>
          </View>
          
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="american"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="angel"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="army"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="beach"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="bike"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="biker/motorcycle"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="cherry"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="city"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="classic"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="colorful"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="designer"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="elegant"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="logo"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="metal"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="modern"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="outdoor"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="punk"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="retro"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="shiny"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="sports"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="stars"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="usa"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="wedding"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="western/cowboy"/>
          </View>
       
          
          <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
            <Choice value="Not-Applicable/Visible"/>
          </View>
        </Choices>
      </View>
    </View>
    
    
    
    
    #**************************Fabric Type [single-Option]*****************************
    
    <View style="display: flex;" visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
      <View style="flex: 70%">
        <Image name="image2" value="$data" zoom="true" zoomControl="true" rotateControl="true"/>
      </View>
      <View style="flex: 30%">
        <Choices name="fabric_type" toName="image" showInLine="true" required="true" choice="single-radio">
          <View style="width:100%">
            <Header name="heading-fabric_type" value="Select Fabric Type [Single-Option]"/>
          </View>
          
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="blended_fabric"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="canvas"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="chambray"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="corduroy"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="crochet"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="denim"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="felt"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="flannel"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="fleece"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="jacquard"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="jersey"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="knit"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="latex"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="mesh"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="shearling"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="softshell"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="terry"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="tweed"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="twill"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="velour/velvet"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="woven"/>
          </View>
       
          
          <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
            <Choice value="Not-Applicable/Visible"/>
          </View>
        </Choices>
      </View>
    </View>
    
    
    
    
    #**************************Outsole Material [single-Option]*****************************
    
    <View style="display: flex;" visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
      <View style="flex: 70%">
        <Image name="image3" value="$data" zoom="true" zoomControl="true" rotateControl="true"/>
      </View>
      <View style="flex: 30%">
        <Choices name="outsole_material" toName="image" showInLine="true" required="true" choice="single-radio">
          <View style="width:100%">
            <Header name="heading-outsole_material" value="Select Outsole Material [Single-Option]"/>
          </View>
          
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="cork"/>
          </View>
       
    
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="faux_leather"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="faux_suede"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="leather"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="patent_leather"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="polyurethane/synthetic"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="rubber"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="suede"/>
          </View>
       
          
          <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
            <Choice value="Not-Applicable/Visible"/>
          </View>
        </Choices>
      </View>
    </View>
    
    
    
    
    #**************************Character [single-Option]*****************************
    
    <View style="display: flex;" visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
      <View style="flex: 70%">
        <Image name="image4" value="$data" zoom="true" zoomControl="true" rotateControl="true"/>
      </View>
      <View style="flex: 30%">
        <Choices name="character" toName="image" showInLine="true" required="true" choice="single-radio">
          <View style="width:100%">
            <Header name="heading-character" value="Select Character [Single-Option]"/>
          </View>
          
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="aladdin"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="aquaman"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="arthur"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="astro_boy"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="batman"/>
          </View>
       
    <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
          
            <Choice value="stitch"/>
          </View>
       
          
          <View visibleWhen="choice-selected" whenTagName="department" whenChoiceValue="men_shoes">
            <Choice value="Not-Applicable/Visible"/>
          </View>
        </Choices>
      </View>
    </View>
    
    
    </View>'
